### ISSUE TITLE
Add more token extraction methods to README

### ISSUE THREAD

**Issue by llistochek** [Sorrow446/Yandex-Music-Downloader#10]
You can add link to this page - https://yandex-music.readthedocs.io/en/main/token.html. It describes all available methods of token extraction.
P.S. Thanks for an amazing tool.

**Comment by Sorrow446** [comment]
I've seen this before and these are only for web tokens unfortunately, even the APK. There's a way to get a proper token through the browser. I'm not sure if I should disclose it as it wasn't intentional by Yandex. I doubt they'd patch it, though.

You're welcome :). I'll start working on the other issues tomorrow.

**Comment by llistochek** [comment]
What's the problem with the web tokens? I personally obtained token via browser extension and it works fine with your program.

**Comment by Sorrow446** [comment]
Just that they don't allow lossless. They're fine to use with the tool, though.

**Comment by llistochek** [comment]
They allow lossless. You can check it yourself. As far as I know OAuth tokens for web, desktop and mobile are equal in functionality and aren't limited in any way.

**Comment by Sorrow446** [comment]
Hm, it didn't when I last tried. Weird.
